######################################################################
# Automatically generated by qmake (2.01a) Fri Jan 27 12:32:16 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += GUInterpreter.h interpreter.h
SOURCES += GUInterpreter.cpp mainwindow.cpp ui.cpp
