######################################################################
# Automatically generated by qmake (2.01a) Sun Jan 29 13:31:19 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += GUInterpreter.h guiwidget.h interpreter.h
SOURCES += GUInterpreter.cpp mainwindow.cpp ui.cpp \
    guiwidget.cpp
